[package]
name = "collate"
version = "0.1.0"
authors = ["Terts Diepraam <terts.diepraam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unic-normal = "0.9.0"
nom = "6.1.2"
